function changeModelForPlot(app,SSITapp)

% This function needs work.


j = find(strcmp(app.MergedModelDropDown.Items,app.MergedModelDropDown.Value));

% Update parameters from selected model.
% app.ReactionsTabOutputs.parameters = {};
% app.ReactionsTabOutputs.parameters(:,2) =  ...
%     {app.DataLoadingAndFittingTabOutputs.ModelMerge.MapAllToEach{j}*...
%     [app.fit_parameters_table.Data{:,2}]'};

np = size(SSITapp.DataLoadingAndFittingTabOutputs.ModelMerge.MapAllToEach{j},1);
app.ModelParameterTable.Data = {'a',1};
app.ModelParameterTable.Data(1:np,2) =  ...
    num2cell(app.DataLoadingAndFittingTabOutputs.ModelMerge.MapAllToEach{j}*...
    [app.fit_parameters_table.Data{:,2}]');

app.ModelParameterTable.Data(1:np,1) =  ...
    app.DataLoadingAndFittingTabOutputs.ModelMerge.ModelData{j}.ModelParameterTable.Data(:,1);

% Change data for selected model
fields = {'FspInitCondField.Value',...
    'ModelInputTable.Data',...
    'ReactionsTabOutputs',...
    'FspPrintTimesField.Value',...
    'FspPiecewiseCheckBox.Value',...
    'ModelReactionTable.Data',...
    'FspConstraintTable.Data',...
    'DataLoadingAndFittingTabOutputs.dataTensor',...
    'DataLoadingAndFittingTabOutputs.fittingOptions',...
    'FspErrorTolField.Value',...
    'ParEstX1CheckBox.Value',...
    'ParEstX2CheckBox.Value',...
    'ParEstX3CheckBox.Value',...
    'FspIntegratorTolerance.Value'};

for i = 1:length(fields)
    eval(['app.',fields{i},'=app.DataLoadingAndFittingTabOutputs.ModelMerge.ModelData{j}.',fields{i},';'])
end

app.LinkDataandModelButton.Enable = 1;


