function SaveCurrentProject(app,pn,fn)

if nargin<3
    [fn,pn] = uiputfile('*.mat','Save Project as','UntitledProject.mat');
    app.FitResultsNameText.Text = fn(1:end-4);
end

fields = {'FspInitCondField.Value',...
    'FspPrintTimesField.Value',...
    'ReactionsTabOutputs',...
    'FittingAlgorithmDropDown.Value',...app.FittingAlgorithmDropDown.Value;
    'FspIntegratorTolerance.Value',...
    'FspErrorTolField.Value',...
    'FspPiecewiseCheckBox.Value',...
    'FspConstraintTable.Data',...
    'FspUseMexCheckBox.Value',...app.FspUseMexCheckBox.Value;
    'FspTabOutputs',...app.FspTabOutputs.fConstraints;
    'DataLoadingAndFittingTabOutputs',...
    'ModelParameterTable.Data'...
    'ModelReactionTable.Data',...
    'ModelList.Text'...
    'ModelInputTable.Data',...
    'fit_parameters_table.Data',...
    'MergeModelConstraints.Data'...
    'NameTable.Data',...
    'MergedModelDropDown.Items',...
    'ParEstX1CheckBox.Value',...
    'ParEstX2CheckBox.Value',...
    'ParEstX3CheckBox.Value',...
    'ParEstFitTimesList.Items',...
    'ParEstFitTimesList.Value',...
    'ParEstPlotTimesDropDown.Items',...
    'ParEstPlotTimesDropDown.Value',...
    'PriorTypeDropDown.Value'};
    

for i=1:length(fields)
    try
        eval(['Loc_app_str.',fields{i},' = app.',fields{i},';'])
    catch
    end
end
vars_to_fit = strcmp(Loc_app_str.fit_parameters_table.Data(:,3),'y');

save([pn,fn],'Loc_app_str','fields','vars_to_fit')

app.DataLoadingAndFittingTabOutputs.backgroundFitDir=pn;
app.DataLoadingAndFittingTabOutputs.backgroundFitFile=fn;
