function RHS = PoissODE_mean(t,x1,in3)
%PoissODE_mean
%    RHS = PoissODE_mean(T,X1,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    01-Oct-2025 20:35:41

Parameter1 = in3(:,1);
Parameter2 = in3(:,2);
RHS = Parameter1-Parameter2.*x1;
end
