function RHS = TwoDTV_mean(t,in2,in3)
%TwoDTV_mean
%    RHS = TwoDTV_mean(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    01-Oct-2025 20:28:36

Parameter1 = in3(:,1);
Parameter2 = in3(:,2);
Parameter3 = in3(:,3);
Parameter4 = in3(:,4);
Parameter5 = in3(:,5);
Parameter6 = in3(:,6);
Parameter7 = in3(:,7);
Parameter8 = in3(:,8);
Parameter9 = in3(:,9);
Parameter10 = in3(:,10);
x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
t2 = Parameter7.*x2;
RHS = [Parameter1-(Parameter2.*x1)./(cos(t)+(x3./Parameter5).^Parameter6+1.0);-t2+Parameter3.*x1-Parameter4.*x2;t2-Parameter8.*x3;Parameter9.*x1-Parameter10.*x4];
end
