function [X_array] = runSingleSsa(x0, S, W, T_array, isTimeVarying, ...
    signalUpdateRate, parameters, ...
    delayedReactions, delayedReactionSchedulingS)

    X_array = runSingleSsaModified(x0, S, W, T_array, isTimeVarying, ...
    signalUpdateRate, parameters, ...
    delayedReactions, delayedReactionSchedulingS);
end