function [mexName, sourceFile] = WriteCppSSA(k,w,S,tprint,fun_name)
% WriteCppSSA
%   Generate a C++ MEX SSA solver from symbolic propensity strings and
%   compile it immediately.
%
% Inputs:
%   k        - parameter vector (used for length checking only)
%   w        - cell array of propensity expressions using x1..xN and k1..kP
%   S        - stoichiometry matrix (Nspec x Nrxn)
%   tprint   - vector of output times
%   fun_name - output mex function name
%
% Outputs:
%   mexName    - compiled mex function name
%   sourceFile - generated C++ source file name

Nspec = size(S,1);
Nrxn = size(S,2);
Nt = length(tprint);

if ~iscell(w)
    error('WriteCppSSA:wMustBeCell','w must be a cell array of propensity strings.');
end
if numel(w) ~= Nrxn
    error('WriteCppSSA:badWLength','Number of propensity expressions must equal number of reactions.');
end

mexName = char(fun_name);
sourceFile = [mexName,'_ssa_mex.cpp'];

fid = fopen(sourceFile,'w');
if fid < 0
    error('WriteCppSSA:fileOpenFailed','Unable to create %s.',sourceFile);
end

cleanupObj = onCleanup(@() fclose(fid));

fprintf(fid,'/* Auto-generated by ssit.ssa.WriteCppSSA */\n');
fprintf(fid,'#include "mex.h"\n');
fprintf(fid,'#include <algorithm>\n');
fprintf(fid,'#include <chrono>\n');
fprintf(fid,'#include <cmath>\n');
fprintf(fid,'#include <cstdint>\n');
fprintf(fid,'#include <random>\n');
fprintf(fid,'#include <vector>\n\n');

fprintf(fid,'static inline std::uint64_t splitmix64(std::uint64_t x) {\n');
fprintf(fid,'    x += 0x9e3779b97f4a7c15ULL;\n');
fprintf(fid,'    x = (x ^ (x >> 30)) * 0xbf58476d1ce4e5b9ULL;\n');
fprintf(fid,'    x = (x ^ (x >> 27)) * 0x94d049bb133111ebULL;\n');
fprintf(fid,'    return x ^ (x >> 31);\n');
fprintf(fid,'}\n\n');

fprintf(fid,'static inline std::uint64_t make_base_seed() {\n');
fprintf(fid,'    const auto now = static_cast<std::uint64_t>(\n');
fprintf(fid,'        std::chrono::high_resolution_clock::now().time_since_epoch().count());\n');
fprintf(fid,'    std::random_device rd;\n');
fprintf(fid,'    const std::uint64_t rdv = (static_cast<std::uint64_t>(rd()) << 32) ^ rd();\n');
fprintf(fid,'    return splitmix64(rdv ^ now);\n');
fprintf(fid,'}\n\n');

fprintf(fid,'static inline double randu01(std::mt19937_64 &rng, std::uniform_real_distribution<double> &U) {\n');
fprintf(fid,'    double r = U(rng);\n');
fprintf(fid,'    return (r <= 0.0) ? 2.2204460492503131e-16 : r;\n');
fprintf(fid,'}\n\n');

fprintf(fid,'extern "C" void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {\n');
fprintf(fid,'    if (nrhs != 3) mexErrMsgIdAndTxt("WriteCppSSA:nrhs", "Expected inputs: x0, N_run, parametersIn.");\n');
fprintf(fid,'    if (nlhs > 1) mexErrMsgIdAndTxt("WriteCppSSA:nlhs", "One output is expected.");\n\n');

fprintf(fid,'    const mwSize Nspec = %d;\n',Nspec);
fprintf(fid,'    const mwSize Nrxn = %d;\n',Nrxn);
fprintf(fid,'    const mwSize Nt = %d;\n',Nt);
fprintf(fid,'    const mwSize NparamExpected = %d;\n\n',numel(k));

fprintf(fid,'    if (!mxIsDouble(prhs[0]) || mxIsComplex(prhs[0])) mexErrMsgIdAndTxt("WriteCppSSA:x0Type", "x0 must be a real double vector.");\n');
fprintf(fid,'    if (mxGetNumberOfElements(prhs[0]) != Nspec) mexErrMsgIdAndTxt("WriteCppSSA:x0Size", "x0 has incorrect length.");\n');
fprintf(fid,'    if (!mxIsDouble(prhs[1]) || mxIsComplex(prhs[1]) || mxGetNumberOfElements(prhs[1]) != 1) mexErrMsgIdAndTxt("WriteCppSSA:nrunType", "N_run must be a real double scalar.");\n');
fprintf(fid,'    if (!mxIsDouble(prhs[2]) || mxIsComplex(prhs[2])) mexErrMsgIdAndTxt("WriteCppSSA:paramType", "parametersIn must be a real double vector.");\n');
fprintf(fid,'    if (mxGetNumberOfElements(prhs[2]) < NparamExpected) mexErrMsgIdAndTxt("WriteCppSSA:paramSize", "parametersIn has fewer entries than expected.");\n\n');

fprintf(fid,'    const double *x0 = mxGetPr(prhs[0]);\n');
fprintf(fid,'    const mwSize N_run = static_cast<mwSize>(mxGetScalar(prhs[1]));\n');
fprintf(fid,'    const double *parametersIn = mxGetPr(prhs[2]);\n\n');

fprintf(fid,'    const double tprint[Nt] = {');
for it = 1:Nt
    if it < Nt
        fprintf(fid,'%.17g, ',tprint(it));
    else
        fprintf(fid,'%.17g',tprint(it));
    end
end
fprintf(fid,'};\n\n');

fprintf(fid,'    const double S[Nspec * Nrxn] = {');
for j = 1:Nrxn
    for i = 1:Nspec
        idx = i + (j-1)*Nspec;
        isLast = (idx == Nspec*Nrxn);
        if ~isLast
            fprintf(fid,'%.17g, ',S(i,j));
        else
            fprintf(fid,'%.17g',S(i,j));
        end
    end
end
fprintf(fid,'};\n\n');

fprintf(fid,'    mwSize dims[3]; dims[0] = Nspec; dims[1] = Nt; dims[2] = N_run;\n');
fprintf(fid,'    plhs[0] = mxCreateNumericArray(3, dims, mxDOUBLE_CLASS, mxREAL);\n');
fprintf(fid,'    double *X = mxGetPr(plhs[0]);\n\n');

fprintf(fid,'    std::vector<double> x(Nspec);\n');
fprintf(fid,'    std::vector<double> xprev(Nspec);\n');
fprintf(fid,'    std::vector<double> props(Nrxn);\n\n');

fprintf(fid,'    const std::uint64_t baseSeed = make_base_seed();\n\n');

fprintf(fid,'    for (mwSize run = 0; run < N_run; ++run) {\n');
fprintf(fid,'        const std::uint64_t seed = splitmix64(baseSeed + static_cast<std::uint64_t>(run) * 0x9e3779b97f4a7c15ULL);\n');
fprintf(fid,'        std::mt19937_64 rng(seed);\n');
fprintf(fid,'        std::uniform_real_distribution<double> U(0.0, 1.0);\n');
fprintf(fid,'        for (mwSize i = 0; i < Nspec; ++i) { x[i] = x0[i]; xprev[i] = x0[i]; }\n');
fprintf(fid,'        double t = tprint[0];\n\n');

fprintf(fid,'        for (mwSize it = 0; it < Nt; ++it) {\n');
fprintf(fid,'            const double tstop = tprint[it];\n');
fprintf(fid,'            while (t < tstop) {\n');
fprintf(fid,'                for (mwSize is = 0; is < Nspec; ++is) xprev[is] = x[is];\n');

for i = 1:Nspec
    fprintf(fid,'                const double x%d = x[%d];\n',i,i-1);
end
for i = 1:numel(k)
    fprintf(fid,'                const double k%d = parametersIn[%d];\n',i,i-1);
end
fprintf(fid,'\n');

for ir = 1:Nrxn
    expr = convertExprToCpp(char(w{ir}));
    fprintf(fid,'                props[%d] = %s;\n',ir-1,expr);
end

fprintf(fid,'                double w0 = 0.0;\n');
fprintf(fid,'                for (mwSize ir = 0; ir < Nrxn; ++ir) w0 += props[ir];\n');
fprintf(fid,'                if (w0 <= 0.0) {\n');
fprintf(fid,'                    t = tstop;\n');
fprintf(fid,'                    break;\n');
fprintf(fid,'                }\n');
fprintf(fid,'\n');
fprintf(fid,'                t += -std::log(randu01(rng,U)) / w0;\n');
fprintf(fid,'                const double r2w0 = randu01(rng,U) * w0;\n');
fprintf(fid,'\n');
fprintf(fid,'                mwSize mu = 0;\n');
fprintf(fid,'                double csum = props[0];\n');
fprintf(fid,'                while ((mu + 1 < Nrxn) && (r2w0 >= csum)) {\n');
fprintf(fid,'                    ++mu;\n');
fprintf(fid,'                    csum += props[mu];\n');
fprintf(fid,'                }\n');
fprintf(fid,'\n');
fprintf(fid,'                for (mwSize is = 0; is < Nspec; ++is) {\n');
fprintf(fid,'                    x[is] += S[is + mu * Nspec];\n');
fprintf(fid,'                }\n');
fprintf(fid,'            }\n');
fprintf(fid,'\n');
fprintf(fid,'            for (mwSize is = 0; is < Nspec; ++is) {\n');
fprintf(fid,'                X[is + it * Nspec + run * Nspec * Nt] = xprev[is];\n');
fprintf(fid,'            }\n');
fprintf(fid,'        }\n');
fprintf(fid,'    }\n');
fprintf(fid,'}\n');

clear cleanupObj;

try
    mex('-R2018a','-O',sourceFile,'-output',mexName);
catch ME
    % Some MATLAB/macOS arm64 setups fail C++ MEX link with adapter symbols
    % under -R2018a even for classic mexFunction entry points. Retry -R2017b.
    msg = string(ME.message);
    needsFallback = contains(msg,"mexFunctionAdapter") || ...
        contains(msg,"mexCreateMexFunction") || ...
        contains(msg,"mexDestroyMexFunction");

    if needsFallback
        try
            mex('-R2017b','-O',sourceFile,'-output',mexName);
        catch ME2
            cSourceFile = [mexName,'_ssa_mex.c'];
            writeCFallbackSource(cSourceFile,k,w,S,tprint);
            try
                mex('-O',cSourceFile,'-output',mexName);
            catch ME3
                error('WriteCppSSA:mexCompileFailed', ...
                    ['Generated %s but compilation failed with both -R2018a and -R2017b; ', ...
                     'C fallback (%s) also failed.\n\nR2018a error:\n%s\n\nR2017b error:\n%s\n\nC fallback error:\n%s'], ...
                    sourceFile,cSourceFile,ME.message,ME2.message,ME3.message);
            end
        end
    else
        error('WriteCppSSA:mexCompileFailed', ...
            'Generated %s but compilation failed:\n%s',sourceFile,ME.message);
    end
end

end

function expr = convertExprToCpp(expr)
% Convert common MATLAB scalar-expression syntax into C++ equivalents.
expr = strtrim(expr);
expr = strrep(expr,'.*','*');
expr = strrep(expr,'./','/');
expr = strrep(expr,'.+','+');
expr = strrep(expr,'.-','-');
expr = regexprep(expr,'\<pi\>','3.14159265358979323846');
expr = regexprep(expr,'\binf\b','INFINITY','ignorecase');

% Convert simple power operators a^b to std::pow(a,b) repeatedly.
powPattern = '([A-Za-z_]\w*|\([^()]*\)|\d+(?:\.\d+)?(?:[eE][+\-]?\d+)?)\s*\^\s*([A-Za-z_]\w*|\([^()]*\)|\d+(?:\.\d+)?(?:[eE][+\-]?\d+)?)';
while contains(expr,'^')
    newExpr = regexprep(expr,powPattern,'std::pow($1,$2)');
    if strcmp(newExpr,expr)
        error('WriteCppSSA:unsupportedPower', ...
            'Unable to convert power operator in expression: %s',expr);
    end
    expr = newExpr;
end

% Prefix common math functions with std:: where needed.
funcs = {'exp','log','log10','sqrt','sin','cos','tan','asin','acos','atan','abs','floor','ceil'};
for i = 1:numel(funcs)
    f = funcs{i};
    expr = regexprep(expr,['(?<![\w:])',f,'\s*\('],['std::',f,'(']);
end

% MATLAB uses max/min; std::max/min are available for scalar values.
expr = regexprep(expr,'(?<![\w:])max\s*\(','std::max(');
expr = regexprep(expr,'(?<![\w:])min\s*\(','std::min(');
end

function writeCFallbackSource(cSourceFile,k,w,S,tprint)
% Write a C MEX fallback for environments where C++ MEX linking is broken.
Nspec = size(S,1);
Nrxn = size(S,2);
Nt = length(tprint);

fid = fopen(cSourceFile,'w');
if fid < 0
    error('WriteCppSSA:fileOpenFailed','Unable to create %s.',cSourceFile);
end
cleanupObj = onCleanup(@() fclose(fid));

fprintf(fid,'/* Auto-generated C fallback by ssit.ssa.WriteCppSSA */\n');
fprintf(fid,'#include "mex.h"\n');
fprintf(fid,'#include <math.h>\n');
fprintf(fid,'#include <stdint.h>\n');
fprintf(fid,'#include <time.h>\n');
fprintf(fid,'#include <stdlib.h>\n\n');

fprintf(fid,'static uint64_t splitmix64(uint64_t x) {\n');
fprintf(fid,'    x += 0x9e3779b97f4a7c15ULL;\n');
fprintf(fid,'    x = (x ^ (x >> 30)) * 0xbf58476d1ce4e5b9ULL;\n');
fprintf(fid,'    x = (x ^ (x >> 27)) * 0x94d049bb133111ebULL;\n');
fprintf(fid,'    return x ^ (x >> 31);\n');
fprintf(fid,'}\n\n');

fprintf(fid,'static inline uint64_t xorshift64star(uint64_t *state) {\n');
fprintf(fid,'    uint64_t x = *state;\n');
fprintf(fid,'    x ^= x >> 12;\n');
fprintf(fid,'    x ^= x << 25;\n');
fprintf(fid,'    x ^= x >> 27;\n');
fprintf(fid,'    *state = x;\n');
fprintf(fid,'    return x * 2685821657736338717ULL;\n');
fprintf(fid,'}\n\n');

fprintf(fid,'static inline double randu01(uint64_t *state) {\n');
fprintf(fid,'    const uint64_t r64 = xorshift64star(state);\n');
fprintf(fid,'    double r = (double)(r64 >> 11) * (1.0 / 9007199254740992.0);\n');
fprintf(fid,'    return (r <= 0.0) ? 2.2204460492503131e-16 : r;\n');
fprintf(fid,'}\n\n');

fprintf(fid,'void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {\n');
fprintf(fid,'    if (nrhs != 3) mexErrMsgIdAndTxt("WriteCppSSA:nrhs", "Expected inputs: x0, N_run, parametersIn.");\n');
fprintf(fid,'    if (nlhs > 1) mexErrMsgIdAndTxt("WriteCppSSA:nlhs", "One output is expected.");\n\n');

fprintf(fid,'#define NSPEC %d\n',Nspec);
fprintf(fid,'#define NRXN %d\n',Nrxn);
fprintf(fid,'#define NT %d\n',Nt);
fprintf(fid,'#define NPARAMEXPECTED %d\n\n',numel(k));

fprintf(fid,'    if (!mxIsDouble(prhs[0]) || mxIsComplex(prhs[0])) mexErrMsgIdAndTxt("WriteCppSSA:x0Type", "x0 must be a real double vector.");\n');
fprintf(fid,'    if (mxGetNumberOfElements(prhs[0]) != NSPEC) mexErrMsgIdAndTxt("WriteCppSSA:x0Size", "x0 has incorrect length.");\n');
fprintf(fid,'    if (!mxIsDouble(prhs[1]) || mxIsComplex(prhs[1]) || mxGetNumberOfElements(prhs[1]) != 1) mexErrMsgIdAndTxt("WriteCppSSA:nrunType", "N_run must be a real double scalar.");\n');
fprintf(fid,'    if (!mxIsDouble(prhs[2]) || mxIsComplex(prhs[2])) mexErrMsgIdAndTxt("WriteCppSSA:paramType", "parametersIn must be a real double vector.");\n');
fprintf(fid,'    if (mxGetNumberOfElements(prhs[2]) < NPARAMEXPECTED) mexErrMsgIdAndTxt("WriteCppSSA:paramSize", "parametersIn has fewer entries than expected.");\n\n');

fprintf(fid,'    const double *x0 = mxGetPr(prhs[0]);\n');
fprintf(fid,'    const mwSize N_run = (mwSize)mxGetScalar(prhs[1]);\n');
fprintf(fid,'    const double *parametersIn = mxGetPr(prhs[2]);\n\n');

fprintf(fid,'    const double tprint[NT] = {');
for it = 1:Nt
    if it < Nt
        fprintf(fid,'%.17g, ',tprint(it));
    else
        fprintf(fid,'%.17g',tprint(it));
    end
end
fprintf(fid,'};\n\n');

fprintf(fid,'    const double S[NSPEC * NRXN] = {');
for j = 1:Nrxn
    for i = 1:Nspec
        idx = i + (j-1)*Nspec;
        isLast = (idx == Nspec*Nrxn);
        if ~isLast
            fprintf(fid,'%.17g, ',S(i,j));
        else
            fprintf(fid,'%.17g',S(i,j));
        end
    end
end
fprintf(fid,'};\n\n');

fprintf(fid,'    mwSize dims[3]; dims[0] = NSPEC; dims[1] = NT; dims[2] = N_run;\n');
fprintf(fid,'    plhs[0] = mxCreateNumericArray(3, dims, mxDOUBLE_CLASS, mxREAL);\n');
fprintf(fid,'    double *X = mxGetPr(plhs[0]);\n\n');

fprintf(fid,'    double *x = (double*)mxMalloc(NSPEC * sizeof(double));\n');
fprintf(fid,'    double *xprev = (double*)mxMalloc(NSPEC * sizeof(double));\n');
fprintf(fid,'    double *props = (double*)mxMalloc(NRXN * sizeof(double));\n');
fprintf(fid,'    if ((x == NULL) || (xprev == NULL) || (props == NULL)) mexErrMsgIdAndTxt("WriteCppSSA:alloc", "Allocation failed.");\n\n');

fprintf(fid,'    const uint64_t baseSeed = splitmix64((((uint64_t)time(NULL)) << 32) ^ (uint64_t)clock() ^ (uint64_t)(uintptr_t)x0 ^ (uint64_t)(uintptr_t)parametersIn);\n\n');

fprintf(fid,'    {\n');
fprintf(fid,'    mwSize run, it, i, is, ir;\n');
fprintf(fid,'    for (run = 0; run < N_run; ++run) {\n');
fprintf(fid,'        uint64_t rngState = splitmix64(baseSeed + ((uint64_t)run * 0x9e3779b97f4a7c15ULL));\n');
fprintf(fid,'        for (i = 0; i < NSPEC; ++i) { x[i] = x0[i]; xprev[i] = x0[i]; }\n');
fprintf(fid,'        {\n');
fprintf(fid,'        double t = tprint[0];\n');
fprintf(fid,'        for (it = 0; it < NT; ++it) {\n');
fprintf(fid,'            const double tstop = tprint[it];\n');
fprintf(fid,'            while (t < tstop) {\n');
fprintf(fid,'                for (is = 0; is < NSPEC; ++is) xprev[is] = x[is];\n');

for i = 1:Nspec
    fprintf(fid,'                const double x%d = x[%d];\n',i,i-1);
end
for i = 1:numel(k)
    fprintf(fid,'                const double k%d = parametersIn[%d];\n',i,i-1);
end
fprintf(fid,'\n');

for ir = 1:Nrxn
    expr = convertExprToC(char(w{ir}));
    fprintf(fid,'                props[%d] = %s;\n',ir-1,expr);
end

fprintf(fid,'                {\n');
fprintf(fid,'                double w0 = 0.0;\n');
fprintf(fid,'                for (ir = 0; ir < NRXN; ++ir) w0 += props[ir];\n');
fprintf(fid,'                if (w0 <= 0.0) { t = tstop; break; }\n');
fprintf(fid,'                t += -log(randu01(&rngState)) / w0;\n');
fprintf(fid,'                {\n');
fprintf(fid,'                const double r2w0 = randu01(&rngState) * w0;\n');
fprintf(fid,'                mwSize mu = 0;\n');
fprintf(fid,'                double csum = props[0];\n');
fprintf(fid,'                while ((mu + 1 < NRXN) && (r2w0 >= csum)) { ++mu; csum += props[mu]; }\n');
fprintf(fid,'                for (is = 0; is < NSPEC; ++is) x[is] += S[is + mu * NSPEC];\n');
fprintf(fid,'                }\n');
fprintf(fid,'                }\n');
fprintf(fid,'            }\n');
fprintf(fid,'            for (is = 0; is < NSPEC; ++is) X[is + it * NSPEC + run * NSPEC * NT] = xprev[is];\n');
fprintf(fid,'        }\n');
fprintf(fid,'        }\n');
fprintf(fid,'    }\n');
fprintf(fid,'    }\n\n');

fprintf(fid,'    mxFree(props);\n');
fprintf(fid,'    mxFree(xprev);\n');
fprintf(fid,'    mxFree(x);\n');
fprintf(fid,'}\n');

clear cleanupObj;
end

function expr = convertExprToC(expr)
% Convert MATLAB scalar-expression syntax into C equivalents.
expr = strtrim(expr);
expr = strrep(expr,'.*','*');
expr = strrep(expr,'./','/');
expr = strrep(expr,'.+','+');
expr = strrep(expr,'.-','-');
expr = regexprep(expr,'\<pi\>','3.14159265358979323846');
expr = regexprep(expr,'\binf\b','HUGE_VAL','ignorecase');

powPattern = '([A-Za-z_]\w*|\([^()]*\)|\d+(?:\.\d+)?(?:[eE][+\-]?\d+)?)\s*\^\s*([A-Za-z_]\w*|\([^()]*\)|\d+(?:\.\d+)?(?:[eE][+\-]?\d+)?)';
while contains(expr,'^')
    newExpr = regexprep(expr,powPattern,'pow($1,$2)');
    if strcmp(newExpr,expr)
        error('WriteCppSSA:unsupportedPower', ...
            'Unable to convert power operator in expression: %s',expr);
    end
    expr = newExpr;
end

% For C fallback, keep plain C math functions (exp/log/sqrt/sin/etc.).
expr = regexprep(expr,'(?<![\w:])abs\s*\(','fabs(');
end
