function symbolicExpression = EricModGR_1_FSP_fun_25(in1,in2)
%EricModGR_1_FSP_fun_25
%    symbolicExpression = EricModGR_1_FSP_fun_25(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:27:05

states2 = in1(2,:);
symbolicExpression = sparse(states2);
end
