function symbolicExpression = EricModGR_2_FSP_fun_32(in1,in2)
%EricModGR_2_FSP_fun_32
%    symbolicExpression = EricModGR_2_FSP_fun_32(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:27:11

states1 = in1(1,:);
symbolicExpression = sparse(states1);
end
