function symbolicExpression = EricModGR_fun_23(in1,in2)
%EricModGR_fun_23
%    symbolicExpression = EricModGR_fun_23(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:26:45

states2 = in1(2,:);
symbolicExpression = sparse(states2);
end
