function symbolicExpression = EricModGR_3_FSP_fun_36(in1,in2)
%EricModGR_3_FSP_fun_36
%    symbolicExpression = EricModGR_3_FSP_fun_36(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:27:15

symbolicExpression = sparse(1.0);
end
