function symbolicExpression = EricModGR_3_FSP_fun_37(in1,in2)
%EricModGR_3_FSP_fun_37
%    symbolicExpression = EricModGR_3_FSP_fun_37(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:27:16

states1 = in1(1,:);
symbolicExpression = sparse(states1);
end
