function symbolicExpression = EricModGR_2_FSP_fun_31(in1,in2)
%EricModGR_2_FSP_fun_31
%    symbolicExpression = EricModGR_2_FSP_fun_31(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:27:10

symbolicExpression = sparse(1.0);
end
