function symbolicExpression = EricModGR_1_FSP_fun_27(in1,in2)
%EricModGR_1_FSP_fun_27
%    symbolicExpression = EricModGR_1_FSP_fun_27(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:27:06

states1 = in1(1,:);
symbolicExpression = sparse(states1);
end
