function symbolicExpression = EricModGR_2_FSP_fun_33(in1,in2)
%EricModGR_2_FSP_fun_33
%    symbolicExpression = EricModGR_2_FSP_fun_33(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:27:11

states2 = in1(2,:);
symbolicExpression = sparse(states2);
end
