function symbolicExpression = EricModGR_fun_19(in1,in2)
%EricModGR_fun_19
%    symbolicExpression = EricModGR_fun_19(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:26:44

states1 = in1(1,:);
symbolicExpression = sparse(states1);
end
