function symbolicExpression = EricModGR_1_FSP_fun_26(in1,in2)
%EricModGR_1_FSP_fun_26
%    symbolicExpression = EricModGR_1_FSP_fun_26(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:27:05

symbolicExpression = sparse(1.0);
end
