function symbolicExpression = EricModGR_1_FSP_fun_24(in1,in2)
%EricModGR_1_FSP_fun_24
%    symbolicExpression = EricModGR_1_FSP_fun_24(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:27:05

states1 = in1(1,:);
symbolicExpression = sparse(states1);
end
