function symbolicExpression = EricModGR_fun_21(in1,in2)
%EricModGR_fun_21
%    symbolicExpression = EricModGR_fun_21(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:26:45

symbolicExpression = sparse(1.0);
end
