function symbolicExpression = EricModGR_3_FSP_fun_35(in1,in2)
%EricModGR_3_FSP_fun_35
%    symbolicExpression = EricModGR_3_FSP_fun_35(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Oct-2023 11:27:15

states2 = in1(2,:);
symbolicExpression = sparse(states2);
end
