classdef MBExperimentDesign
    %MBExperimentDesign encapsulates how many observations an experimenter
    %should seek to obtain within a single experiment (or single round of a
    %sequence of experiments). 

    properties (Dependent)
        Configurations
        NumberOfConfigurations
        NumberOfObservations
    end

    properties
        % uint64 is used here to automatically require that the number of
        % observations is always a non-negative integer.
        
        ConfigurationToNumObservationsMap = ...
            configureDictionary("MBExperimentConfiguration", "uint64")
    end

    methods (Access = private)
        function [Obs, inputConfigurations, times] = ...
                buildObservationMatrix(obj)
            % We need to extract the input configurations and measurement
            % times from the map. We know that there will be no more input
            % configurations than the number of keys, though possibly
            % fewer. We have no knowledge of how many measurement times
            % exist.

            k = obj.ConfigurationToNumObservationsMap.keys();
            inputConfigurations = createArray(1, length(k), ...
                "MBExperimentInputConfiguration");
            times = [];

            for keyIdx = 1:length(k)
                curExperimentConfiguration = ...
                    obj.ConfigurationToNumObservationsMap(k(keyIdx));
                inputConfigurations(keyIdx) = ...
                    curExperimentConfiguration.InputConfiguration;
                times = horzcat(times, ...
                    curExperimentConfiguration.TimeConfigurable.Values);
            end

            inputConfigurations = unique(inputConfigurations);
            times = unique(sort(times));

            Obs = zeros(length(inputConfigurations), length(times));
        end
    end % Private methods

    methods
        function configs = get.Configurations(obj)
            configs = obj.ConfigurationToNumObservationsMap.keys();
        end

        function numConfigs = get.NumberOfConfigurations(obj)
            numConfigs = obj.ConfigurationToNumObservationsMap.numEntries;
        end

        function numObservations = get.NumberOfObservations(obj)
            numObservations = ...
                sum(obj.ConfigurationToNumObservationsMap.values);
        end

        function [Obs, inputConfigurations, times] = ...
                getAsObservationMatrix(obj)
            %getAsObservationMatrix returns a matrix containing the number
            %of observations to be made at each input configuration (row)
            %and measurement time (column). This is the format generated by
            %methods such as optimizeCellCounts.

            [Obs, inputConfigurations, times] = obj.buildObservationMatrix;
            Obs = uint64(Obs);

            for inputConfigIdx = 1:length(inputConfigurations)
                for timeIdx = 1:length(times)
                    curConfig = MBExperimentConfiguration();
                    curConfig.InputConfiguration = ...
                        inputConfigurations(inputConfigIdx);
                    curConfig.TimeConfigurable.Values = times(timeIdx);

                    Obs(inputConfigIdx, timeIdx) = ...
                        obj.ConfigurationToNumObservationsMap(curConfig);
                end
            end
        end % getAsObservationMatrix

        function observations = getObservationsForConfiguration(...
                obj, configuration)
            arguments
                obj (1, 1) MBExperimentDesign
                configuration (1, 1) MBExperimentConfiguration ...
                    {mustHaveSingleValueForAllConfigurables(configuration)}                
            end

            observations = ...
                obj.ConfigurationToNumObservationsMap(configuration);
        end

        function [Obs, inputConfigurations, times] = ...
                getTheoreticalObservationMatrix(obj)
            %getTheoreticalObservationMatrix returns a matrix containing
            %the theoretical maximum number of observations that could be
            %made at each input configuration (row) and measurement time
            %(column); this is the format generated by methods such as
            %optimizeObservationCounts. This method exists because not all
            %combinations of input configuration and measurement time might
            %be available, so zero observations are theoretically possible
            %in such cases, whereas infinitely many observations are
            %possible generally.

            [Obs, inputConfigurations, times] = obj.buildObservationMatrix;
            
            for inputConfigIdx = 1:length(inputConfigurations)
                for timeIdx = 1:length(times)
                    curConfig = MBExperimentConfiguration();
                    curConfig.InputConfiguration = ...
                        inputConfigurations(inputConfigIdx);
                    curConfig.TimeConfigurable.Values = times(timeIdx);

                    % If the current configuration IS a key of the map,
                    % that means it is an available configuration, and
                    % therefore, arbitrarily many observations could be
                    % possible. If it is NOT a key, then no observations
                    % are possible, so we will leave the corresponding
                    % entry of the observation matrix at zero.

                    if obj.ConfigurationToNumObservationsMap.isKey(curConfig)
                        Obs(inputConfigIdx, timeIdx) = inf;
                    end
                end
            end
        end % getTheoreticalObservationMatrix

        function obj = setFromObservationMatrix(...
                obj, Obs, inputConfigurations, times)
            %setFromObservationMatrix accepts a matrix containing the
            %number of observations to be made at each input configuration
            %(row) and measurement time (column); this is the format
            %generated by methods such as optimizeObservationCounts. It
            %also requires a list of lists of input configurations and
            %measurement times corresponding to the matrix.

            arguments
                obj (1, 1) MBExperimentDesign
                Obs (:, :) uint64
                inputConfigurations (1, :) ...
                    MBExperimentInputConfiguration {mustBeNonempty, ...
                    mustHaveSingleValueForAllConfigurables(inputConfigurations)} 
                times (1, :) double {mustBeNonempty, mustBeNonnegative}
            end

            [rows, cols] = size(Obs);
            if rows ~= length(inputConfigurations)
                error("Cannot set design from matrix with " + ...
                    "incompatible number of input configurations")
            end
            if cols ~= length(times)
                error("Cannot set design from matrix with " + ...
                    "incompatible number of measurement times")
            end

            % Having verified that the inputs are mutually consistent,
            % reset the dictionary, then iterate over the observation
            % matrix and populate the dictionary with the corresponding
            % (key, value) pair.

            obj.ConfigurationToNumObservationsMap = ...
                configureDictionary("MBExperimentConfiguration", "uint64");

            for inputConfigIdx = 1:rows
                for timeIdx = 1:cols
                    curConfig = MBExperimentConfiguration();
                    curConfig.InputConfiguration = ...
                        inputConfigurations(inputConfigIdx);
                    curConfig.TimeConfigurable.Values = times(timeIdx);

                    obj.ConfigurationToNumObservationsMap(curConfig) = ...
                        Obs(inputConfigIdx, timeIdx);
                end
            end
        end % setFromObservationMatrix

        function obj = setObservationsForConfiguration(...
                obj, configuration, observations)
            arguments
                obj (1, 1) MBExperimentDesign
                configuration (1, 1) MBExperimentConfiguration ...
                    {mustHaveSingleValueForAllConfigurables(configuration)}
                observations (1, 1) uint64
            end

            obj.ConfigurationToNumObservationsMap(configuration) = ...
                observations;
        end
    end % Public methods
end % MBExperimentDesign

function mustHaveSingleValueForAllConfigurables(configurations)
arguments
    configurations (1, :) MBExperimentConfiguration
end

% Here, we validate that every configurable in each configuration only has 
% a single value, via the getSingleValue method on each configurable, since
% that method will error and print the values if there are multiple of
% them.

for configIdx = 1:length(configurations)
    curConfig = configurations(configIdx);
    for inputConfigIdx = 1:length(curConfig.InputConfigurables)
        curInputConfigurable = ...
            curConfig.InputConfigurables(inputConfigIdx);
        curInputConfigurable.getSingleValue();
    end

    curConfig.TimeConfigurable.getSingleValue();
end

end