function createfigure(Y1, Y2, Y3, Y4, Y5, Y6, Y7, Y8, Y9, Y10, Y11, Y12, Y13, Y14, Y15)
%CREATEFIGURE(Y1, Y2, Y3, Y4, Y5, Y6, Y7, Y8, Y9, Y10, Y11, Y12, Y13, Y14, Y15)
%  Y1:  vector of stairs y data
%  Y2:  vector of stairs y data
%  Y3:  vector of stairs y data
%  Y4:  vector of stairs y data
%  Y5:  vector of stairs y data
%  Y6:  vector of stairs y data
%  Y7:  vector of stairs y data
%  Y8:  vector of stairs y data
%  Y9:  vector of stairs y data
%  Y10:  vector of stairs y data
%  Y11:  vector of stairs y data
%  Y12:  vector of stairs y data
%  Y13:  vector of stairs y data
%  Y14:  vector of stairs y data
%  Y15:  vector of stairs y data

%  Auto-generated by MATLAB on 29-Jul-2025 00:29:06

% Create figure
figure1 = figure('Name','Marg. Dist. Sensitivities of x5 at t=20');

% Create subplot
subplot1 = subplot(4,4,1,'Parent',figure1);
hold(subplot1,'on');

% Create stairs
stairs(Y1,'Parent',subplot1,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('k12','FontSize',24);

hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'FontSize',18,'XTick',[0 10 20]);
% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.348219559422822 0.767258064516129 0.141427442511414 0.140857431349191]);
hold(axes1,'on');

% Create stairs
stairs(Y2,'Parent',axes1,'LineWidth',2,'Color',[0 0 1]);

% Create ylabel
ylabel('sensitivity','FontSize',32);

% Create title
title('k23','FontSize',24);

hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',18,'XTick',[0 10 20]);
% Create subplot
subplot2 = subplot(4,4,3,'Parent',figure1);
hold(subplot2,'on');

% Create stairs
stairs(Y3,'Parent',subplot2,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('k34','FontSize',24);

hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'FontSize',18,'XTick',[0 10 20]);
% Create subplot
subplot3 = subplot(4,4,4,'Parent',figure1);
hold(subplot3,'on');

% Create stairs
stairs(Y4,'Parent',subplot3,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('k21','FontSize',24);

hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'FontSize',18,'XTick',[0 10 20]);
% Create subplot
subplot4 = subplot(4,4,5,'Parent',figure1);
hold(subplot4,'on');

% Create stairs
stairs(Y5,'Parent',subplot4,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('k32','FontSize',24);

hold(subplot4,'off');
% Set the remaining axes properties
set(subplot4,'FontSize',18,'XTick',[0 10 20],'YTick',[-0.04 0 0.04]);
% Create subplot
subplot5 = subplot(4,4,6,'Parent',figure1);
hold(subplot5,'on');

% Create stairs
stairs(Y6,'Parent',subplot5,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('k43','FontSize',24);

hold(subplot5,'off');
% Set the remaining axes properties
set(subplot5,'FontSize',18,'XTick',[0 10 20]);
% Create subplot
subplot6 = subplot(4,4,7,'Parent',figure1);
hold(subplot6,'on');

% Create stairs
stairs(Y7,'Parent',subplot6,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('kr1','FontSize',24);

hold(subplot6,'off');
% Set the remaining axes properties
set(subplot6,'FontSize',18,'XTick',[0 10 20]);
% Create subplot
subplot7 = subplot(4,4,8,'Parent',figure1);
hold(subplot7,'on');

% Create stairs
stairs(Y8,'Parent',subplot7,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('kr2','FontSize',24);

hold(subplot7,'off');
% Set the remaining axes properties
set(subplot7,'FontSize',18,'XTick',[0 10 20]);
% Create subplot
subplot8 = subplot(4,4,9,'Parent',figure1);
hold(subplot8,'on');

% Create stairs
stairs(Y9,'Parent',subplot8,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('kr3','FontSize',24);

hold(subplot8,'off');
% Set the remaining axes properties
set(subplot8,'FontSize',18,'XTick',[0 10 20]);
% Create subplot
subplot9 = subplot(4,4,10,'Parent',figure1);
hold(subplot9,'on');

% Create stairs
stairs(Y10,'Parent',subplot9,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('kr4','FontSize',24);

hold(subplot9,'off');
% Set the remaining axes properties
set(subplot9,'FontSize',18,'XTick',[0 10 20]);
% Create subplot
subplot10 = subplot(4,4,11,'Parent',figure1);
hold(subplot10,'on');

% Create stairs
stairs(Y11,'Parent',subplot10,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('dr','FontSize',24);

hold(subplot10,'off');
% Set the remaining axes properties
set(subplot10,'FontSize',18,'XTick',[0 10 20],'YTick',[-0.04 0 0.04]);
% Create subplot
subplot11 = subplot(4,4,12,'Parent',figure1);
hold(subplot11,'on');

% Create stairs
stairs(Y12,'Parent',subplot11,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('a0','FontSize',24);

hold(subplot11,'off');
% Set the remaining axes properties
set(subplot11,'FontSize',18,'XTick',[0 10 20]);
% Create subplot
subplot12 = subplot(4,4,13,'Parent',figure1);
hold(subplot12,'on');

% Create stairs
stairs(Y13,'Parent',subplot12,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('a1','FontSize',24);

hold(subplot12,'off');
% Set the remaining axes properties
set(subplot12,'FontSize',18,'XTick',[0 10 20]);
% Create subplot
subplot13 = subplot(4,4,14,'Parent',figure1);
hold(subplot13,'on');

% Create stairs
stairs(Y14,'Parent',subplot13,'LineWidth',2,'Color',[0 0 1]);

% Create xlabel
xlabel('mRNA','FontSize',30);

% Create title
title('r1','FontSize',24);

hold(subplot13,'off');
% Set the remaining axes properties
set(subplot13,'FontSize',18,'XTick',[0 10 20]);
% Create subplot
subplot14 = subplot(4,4,15,'Parent',figure1);
hold(subplot14,'on');

% Create stairs
stairs(Y15,'Parent',subplot14,'LineWidth',2,'Color',[0 0 1]);

% Create title
title('r2','FontSize',24);

hold(subplot14,'off');
% Set the remaining axes properties
set(subplot14,'FontSize',18,'XTick',[0 10 20]);
